---
# ######################################################################
# pypiserver docker-compose examples
# ######################################################################
# The below examples illustrate different ways that pypiserver may be
# configured with docker-compose (and by extension, with Docker) to
# serve your python packages.
#
# Most of the configuration options detailed below can be mixed and
# matched as desired.
# ######################################################################

version: "3.3"

services:
    pypiserver-authenticated:
        image: pypiserver/pypiserver:latest
        volumes:
            - type: bind
              source: ./auth
              target: /data/auth
        command: -P /data/auth/.htpasswd -a update,download,list /data/packages
        ports:
            - "6969:8080"
